// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGwX655v6DJwkCqgwI7BTc_MgKeWyM-48',
    appId: '1:792140130290:web:5831062af5bf3c6de76d6b',
    messagingSenderId: '792140130290',
    projectId: 'blooddochallenge-09052024',
    authDomain: 'blooddochallenge-09052024.firebaseapp.com',
    storageBucket: 'blooddochallenge-09052024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaFAZlV0AnROPz1bjj3GQvrPFlPEUuALo',
    appId: '1:792140130290:android:1ee4ee021c12aff6e76d6b',
    messagingSenderId: '792140130290',
    projectId: 'blooddochallenge-09052024',
    storageBucket: 'blooddochallenge-09052024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs4U13r-WWP2Xx3sB3bkx1alWcZuFIUHw',
    appId: '1:792140130290:ios:9897f9c1277cbe30e76d6b',
    messagingSenderId: '792140130290',
    projectId: 'blooddochallenge-09052024',
    storageBucket: 'blooddochallenge-09052024.appspot.com',
    iosBundleId: 'com.example.blooddochallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs4U13r-WWP2Xx3sB3bkx1alWcZuFIUHw',
    appId: '1:792140130290:ios:9897f9c1277cbe30e76d6b',
    messagingSenderId: '792140130290',
    projectId: 'blooddochallenge-09052024',
    storageBucket: 'blooddochallenge-09052024.appspot.com',
    iosBundleId: 'com.example.blooddochallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGwX655v6DJwkCqgwI7BTc_MgKeWyM-48',
    appId: '1:792140130290:web:99578063fff2d501e76d6b',
    messagingSenderId: '792140130290',
    projectId: 'blooddochallenge-09052024',
    authDomain: 'blooddochallenge-09052024.firebaseapp.com',
    storageBucket: 'blooddochallenge-09052024.appspot.com',
  );

}